---
- name: postgresql
  hosts: ansible2
  vars:
    names:
      - python3-psycopg2
      - '@postgresql'
  tasks:
  - name: install
    dnf:
      name: "{{ item }}"
      state: installed
    loop: "{{ names }}"
#  - name: Check if PostgreSQL database is initialized.
#    stat:
#      path: "{{ postgresql_data_dir }}/PG_VERSION"
#    register: pgdata_dir_version
 
  - name: Ensure PostgreSQL database is initialized.
    command: "/usr/bin/postgresql-setup --initdb"
    become: true
    become_user: "postgres"
  
  - name: smt
    postgresql_db:
      name: db
      login_user: postgres
      login_password: redhat
    
