---
- name: install and start postgresql
  hosts: ansible2
  vars:
    packages:
      - postgresql
      - postgresql-server
      - postgresql-contrib
      - python3-psycopg2
  tasks: 
  - name: install package
    yum:
      name: "{{ item }}"
      state: installed
    loop: "{{ packages }}" 
  - name: start the service
    service:
      name: postgresql
      state: started
      enabled: yes
  
  - name: smt
    postgresql_db:
      name: ansible_added
      login_user: postgres
      login_password: redhat

