--- 
- name: install and start postgresql
  hosts: all
  vars:
    packages:
      - postgresql
      - postgresql-server
      - postgresql-contrib
      - python3-psycopg2
  tasks:
  - name: install package
    yum:
      name: "{{ item }}"
      state: installed
    loop: "{{ packages }}"
  
  - name: PostgreSQL | Check whether the postgres data directory is initialized | RedHat
    stat:
      path: "/var/lib/pgsql/data/PG_VERSION"
    register: pgdata_dir_initialized
 
  - name: Ensure PostgreSQL database is initialized.
    command: "initdb -D /var/lib/pgsql/data"
    become: true
    become_user: postgres
    become_method: sudo
    when: not pgdata_dir_initialized.stat.exists  

  - name: start the service
    service:
      name: postgresql
      state: started
      enabled: yes
  
  - name: start the firewall if not running
    service: 
      name: firewalld
      state: started
      enabled: yes
     

  - name: enable postgresql through firewall
    firewalld:
      service: postgresql
      state: enabled
      permanent: yes
      immediate: yes
